{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "asyncio\n",
    "\n",
    "# Coroutines and Tasks\n",
    "\n",
    "This section outlines high-level asyncio APIs to work with coroutines\n",
    "and Tasks.\n",
    "\n",
    "## Coroutines\n",
    "\n",
    "`Coroutines <coroutine>` declared with the async/await syntax is the\n",
    "preferred way of writing asyncio applications. For example, the\n",
    "following snippet of code prints \"hello\", waits 1 second, and then\n",
    "prints \"world\":\n",
    "\n",
    "    >>> import asyncio\n",
    "\n",
    "    >>> async def main():\n",
    "    ...     print('hello')\n",
    "    ...     await asyncio.sleep(1)\n",
    "    ...     print('world')\n",
    "\n",
    "    >>> asyncio.run(main())\n",
    "    hello\n",
    "    world\n",
    "\n",
    "Note that simply calling a coroutine will not schedule it to be\n",
    "executed:\n",
    "\n",
    "    >>> main()\n",
    "    <coroutine object main at 0x1053bb7c8>\n",
    "\n",
    "To actually run a coroutine, asyncio provides three main mechanisms:\n",
    "\n",
    "-   The `asyncio.run` function to run the top-level entry point \"main()\"\n",
    "    function (see the above example.)\n",
    "\n",
    "-   Awaiting on a coroutine. The following snippet of code will print\n",
    "    \"hello\" after waiting for 1 second, and then print \"world\" after\n",
    "    waiting for *another* 2 seconds:\n",
    "\n",
    "        import asyncio\n",
    "        import time\n",
    "\n",
    "        async def say_after(delay, what):\n",
    "            await asyncio.sleep(delay)\n",
    "            print(what)\n",
    "\n",
    "        async def main():\n",
    "            print(f\"started at {time.strftime('%X')}\")\n",
    "\n",
    "            await say_after(1, 'hello')\n",
    "            await say_after(2, 'world')\n",
    "\n",
    "            print(f\"finished at {time.strftime('%X')}\")\n",
    "\n",
    "        asyncio.run(main())\n",
    "\n",
    "    Expected output:\n",
    "\n",
    "        started at 17:13:52\n",
    "        hello\n",
    "        world\n",
    "        finished at 17:13:55\n",
    "\n",
    "-   The `asyncio.create_task` function to run coroutines concurrently as\n",
    "    asyncio `Tasks <Task>`.\n",
    "\n",
    "    Let's modify the above example and run two `say_after` coroutines\n",
    "    *concurrently*:\n",
    "\n",
    "        async def main():\n",
    "            task1 = asyncio.create_task(\n",
    "                say_after(1, 'hello'))\n",
    "\n",
    "            task2 = asyncio.create_task(\n",
    "                say_after(2, 'world'))\n",
    "\n",
    "            print(f\"started at {time.strftime('%X')}\")\n",
    "\n",
    "            # Wait until both tasks are completed (should take\n",
    "            # around 2 seconds.)\n",
    "            await task1\n",
    "            await task2\n",
    "\n",
    "            print(f\"finished at {time.strftime('%X')}\")\n",
    "\n",
    "    Note that expected output now shows that the snippet runs 1 second\n",
    "    faster than before:\n",
    "\n",
    "        started at 17:14:32\n",
    "        hello\n",
    "        world\n",
    "        finished at 17:14:34\n",
    "\n",
    "## Awaitables\n",
    "\n",
    "We say that an object is an **awaitable** object if it can be used in an\n",
    "`await` expression. Many asyncio APIs are designed to accept awaitables.\n",
    "\n",
    "There are three main types of *awaitable* objects: **coroutines**,\n",
    "**Tasks**, and **Futures**.\n",
    "\n",
    "**Coroutines**\n",
    "\n",
    "Python coroutines are *awaitables* and therefore can be awaited from\n",
    "other coroutines:\n",
    "\n",
    "    import asyncio\n",
    "\n",
    "    async def nested():\n",
    "        return 42\n",
    "\n",
    "    async def main():\n",
    "        # Nothing happens if we just call \"nested()\".\n",
    "        # A coroutine object is created but not awaited,\n",
    "        # so it *won't run at all*.\n",
    "        nested()\n",
    "\n",
    "        # Let's do it differently now and await it:\n",
    "        print(await nested())  # will print \"42\".\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "Important\n",
    "\n",
    "In this documentation the term \"coroutine\" can be used for two closely\n",
    "related concepts:\n",
    "\n",
    "-   a *coroutine function*: an `async def` function;\n",
    "-   a *coroutine object*: an object returned by calling a *coroutine\n",
    "    function*.\n",
    "\n",
    "**Tasks**\n",
    "\n",
    "*Tasks* are used to schedule coroutines *concurrently*.\n",
    "\n",
    "When a coroutine is wrapped into a *Task* with functions like\n",
    "`asyncio.create_task` the coroutine is automatically scheduled to run\n",
    "soon:\n",
    "\n",
    "    import asyncio\n",
    "\n",
    "    async def nested():\n",
    "        return 42\n",
    "\n",
    "    async def main():\n",
    "        # Schedule nested() to run soon concurrently\n",
    "        # with \"main()\".\n",
    "        task = asyncio.create_task(nested())\n",
    "\n",
    "        # \"task\" can now be used to cancel \"nested()\", or\n",
    "        # can simply be awaited to wait until it is complete:\n",
    "        await task\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "**Futures**\n",
    "\n",
    "A `Future` is a special **low-level** awaitable object that represents\n",
    "an **eventual result** of an asynchronous operation.\n",
    "\n",
    "When a Future object is *awaited* it means that the coroutine will wait\n",
    "until the Future is resolved in some other place.\n",
    "\n",
    "Future objects in asyncio are needed to allow callback-based code to be\n",
    "used with async/await.\n",
    "\n",
    "Normally **there is no need** to create Future objects at the\n",
    "application level code.\n",
    "\n",
    "Future objects, sometimes exposed by libraries and some asyncio APIs,\n",
    "can be awaited:\n",
    "\n",
    "    async def main():\n",
    "        await function_that_returns_a_future_object()\n",
    "\n",
    "        # this is also valid:\n",
    "        await asyncio.gather(\n",
    "            function_that_returns_a_future_object(),\n",
    "            some_python_coroutine()\n",
    "        )\n",
    "\n",
    "A good example of a low-level function that returns a Future object is\n",
    "`loop.run_in_executor`.\n",
    "\n",
    "## Creating Tasks\n",
    "\n",
    "create_task(coro, \\*, name=None, context=None)\n",
    "\n",
    "Wrap the *coro* `coroutine <coroutine>` into a `Task` and schedule its\n",
    "execution. Return the Task object.\n",
    "\n",
    "If *name* is not `None`, it is set as the name of the task using\n",
    "`Task.set_name`.\n",
    "\n",
    "An optional keyword-only *context* argument allows specifying a custom\n",
    "`contextvars.Context` for the *coro* to run in. The current context copy\n",
    "is created when no *context* is provided.\n",
    "\n",
    "The task is executed in the loop returned by `get_running_loop`,\n",
    "`RuntimeError` is raised if there is no running loop in current thread.\n",
    "\n",
    "Important\n",
    "\n",
    "Save a reference to the result of this function, to avoid a task\n",
    "disappearing mid execution.\n",
    "\n",
    "3.7\n",
    "\n",
    "3.8 Added the *name* parameter.\n",
    "\n",
    "3.11 Added the *context* parameter.\n",
    "\n",
    "## Sleeping\n",
    "\n",
    "sleep(delay, result=None)\n",
    "\n",
    "Block for *delay* seconds.\n",
    "\n",
    "If *result* is provided, it is returned to the caller when the coroutine\n",
    "completes.\n",
    "\n",
    "`sleep()` always suspends the current task, allowing other tasks to run.\n",
    "\n",
    "Setting the delay to 0 provides an optimized path to allow other tasks\n",
    "to run. This can be used by long-running functions to avoid blocking the\n",
    "event loop for the full duration of the function call.\n",
    "\n",
    "Example of coroutine displaying the current date every second for 5\n",
    "seconds:\n",
    "\n",
    "    import asyncio\n",
    "    import datetime\n",
    "\n",
    "    async def display_date():\n",
    "        loop = asyncio.get_running_loop()\n",
    "        end_time = loop.time() + 5.0\n",
    "        while True:\n",
    "            print(datetime.datetime.now())\n",
    "            if (loop.time() + 1.0) >= end_time:\n",
    "                break\n",
    "            await asyncio.sleep(1)\n",
    "\n",
    "    asyncio.run(display_date())\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "## Running Tasks Concurrently\n",
    "\n",
    "gather(\\*aws, return_exceptions=False)\n",
    "\n",
    "Run `awaitable objects <asyncio-awaitables>` in the *aws* sequence\n",
    "*concurrently*.\n",
    "\n",
    "If any awaitable in *aws* is a coroutine, it is automatically scheduled\n",
    "as a Task.\n",
    "\n",
    "If all awaitables are completed successfully, the result is an aggregate\n",
    "list of returned values. The order of result values corresponds to the\n",
    "order of awaitables in *aws*.\n",
    "\n",
    "If *return_exceptions* is `False` (default), the first raised exception\n",
    "is immediately propagated to the task that awaits on `gather()`. Other\n",
    "awaitables in the *aws* sequence **won't be cancelled** and will\n",
    "continue to run.\n",
    "\n",
    "If *return_exceptions* is `True`, exceptions are treated the same as\n",
    "successful results, and aggregated in the result list.\n",
    "\n",
    "If `gather()` is *cancelled*, all submitted awaitables (that have not\n",
    "completed yet) are also *cancelled*.\n",
    "\n",
    "If any Task or Future from the *aws* sequence is *cancelled*, it is\n",
    "treated as if it raised `CancelledError` -- the `gather()` call is\n",
    "**not** cancelled in this case. This is to prevent the cancellation of\n",
    "one submitted Task/Future to cause other Tasks/Futures to be cancelled.\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "Example:\n",
    "\n",
    "    import asyncio\n",
    "\n",
    "    async def factorial(name, number):\n",
    "        f = 1\n",
    "        for i in range(2, number + 1):\n",
    "            print(f\"Task {name}: Compute factorial({number}), currently i={i}...\")\n",
    "            await asyncio.sleep(1)\n",
    "            f *= i\n",
    "        print(f\"Task {name}: factorial({number}) = {f}\")\n",
    "        return f\n",
    "\n",
    "    async def main():\n",
    "        # Schedule three calls *concurrently*:\n",
    "        L = await asyncio.gather(\n",
    "            factorial(\"A\", 2),\n",
    "            factorial(\"B\", 3),\n",
    "            factorial(\"C\", 4),\n",
    "        )\n",
    "        print(L)\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "    # Expected output:\n",
    "    #\n",
    "    #     Task A: Compute factorial(2), currently i=2...\n",
    "    #     Task B: Compute factorial(3), currently i=2...\n",
    "    #     Task C: Compute factorial(4), currently i=2...\n",
    "    #     Task A: factorial(2) = 2\n",
    "    #     Task B: Compute factorial(3), currently i=3...\n",
    "    #     Task C: Compute factorial(4), currently i=3...\n",
    "    #     Task B: factorial(3) = 6\n",
    "    #     Task C: Compute factorial(4), currently i=4...\n",
    "    #     Task C: factorial(4) = 24\n",
    "    #     [2, 6, 24]\n",
    "\n",
    "Note\n",
    "\n",
    "If *return_exceptions* is False, cancelling gather() after it has been\n",
    "marked done won't cancel any submitted awaitables. For instance, gather\n",
    "can be marked done after propagating an exception to the caller,\n",
    "therefore, calling `gather.cancel()` after catching an exception (raised\n",
    "by one of the awaitables) from gather won't cancel any other awaitables.\n",
    "\n",
    "3.7 If the *gather* itself is cancelled, the cancellation is propagated\n",
    "regardless of *return_exceptions*.\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "3.10 Deprecation warning is emitted if no positional arguments are\n",
    "provided or not all positional arguments are Future-like objects and\n",
    "there is no running event loop.\n",
    "\n",
    "## Shielding From Cancellation\n",
    "\n",
    "shield(aw)\n",
    "\n",
    "Protect an `awaitable object <asyncio-awaitables>` from being\n",
    "`cancelled <Task.cancel>`.\n",
    "\n",
    "If *aw* is a coroutine it is automatically scheduled as a Task.\n",
    "\n",
    "The statement:\n",
    "\n",
    "    res = await shield(something())\n",
    "\n",
    "is equivalent to:\n",
    "\n",
    "    res = await something()\n",
    "\n",
    "*except* that if the coroutine containing it is cancelled, the Task\n",
    "running in `something()` is not cancelled. From the point of view of\n",
    "`something()`, the cancellation did not happen. Although its caller is\n",
    "still cancelled, so the \"await\" expression still raises a\n",
    "`CancelledError`.\n",
    "\n",
    "If `something()` is cancelled by other means (i.e. from within itself)\n",
    "that would also cancel `shield()`.\n",
    "\n",
    "If it is desired to completely ignore cancellation (not recommended) the\n",
    "`shield()` function should be combined with a try/except clause, as\n",
    "follows:\n",
    "\n",
    "    try:\n",
    "        res = await shield(something())\n",
    "    except CancelledError:\n",
    "        res = None\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "3.10 Deprecation warning is emitted if *aw* is not Future-like object\n",
    "and there is no running event loop.\n",
    "\n",
    "## Timeouts\n",
    "\n",
    "wait_for(aw, timeout)\n",
    "\n",
    "Wait for the *aw* `awaitable <asyncio-awaitables>` to complete with a\n",
    "timeout.\n",
    "\n",
    "If *aw* is a coroutine it is automatically scheduled as a Task.\n",
    "\n",
    "*timeout* can either be `None` or a float or int number of seconds to\n",
    "wait for. If *timeout* is `None`, block until the future completes.\n",
    "\n",
    "If a timeout occurs, it cancels the task and raises `TimeoutError`.\n",
    "\n",
    "To avoid the task `cancellation <Task.cancel>`, wrap it in `shield`.\n",
    "\n",
    "The function will wait until the future is actually cancelled, so the\n",
    "total wait time may exceed the *timeout*. If an exception happens during\n",
    "cancellation, it is propagated.\n",
    "\n",
    "If the wait is cancelled, the future *aw* is also cancelled.\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "Example:\n",
    "\n",
    "    async def eternity():\n",
    "        # Sleep for one hour\n",
    "        await asyncio.sleep(3600)\n",
    "        print('yay!')\n",
    "\n",
    "    async def main():\n",
    "        # Wait for at most 1 second\n",
    "        try:\n",
    "            await asyncio.wait_for(eternity(), timeout=1.0)\n",
    "        except TimeoutError:\n",
    "            print('timeout!')\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "    # Expected output:\n",
    "    #\n",
    "    #     timeout!\n",
    "\n",
    "3.7 When *aw* is cancelled due to a timeout, `wait_for` waits for *aw*\n",
    "to be cancelled. Previously, it raised `TimeoutError` immediately.\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "## Waiting Primitives\n",
    "\n",
    "wait(aws, \\*, timeout=None, return_when=ALL_COMPLETED)\n",
    "\n",
    "Run `~asyncio.Future` and `~asyncio.Task` instances in the *aws*\n",
    "iterable concurrently and block until the condition specified by\n",
    "*return_when*.\n",
    "\n",
    "The *aws* iterable must not be empty.\n",
    "\n",
    "Returns two sets of Tasks/Futures: `(done, pending)`.\n",
    "\n",
    "Usage:\n",
    "\n",
    "    done, pending = await asyncio.wait(aws)\n",
    "\n",
    "*timeout* (a float or int), if specified, can be used to control the\n",
    "maximum number of seconds to wait before returning.\n",
    "\n",
    "Note that this function does not raise `TimeoutError`. Futures or Tasks\n",
    "that aren't done when the timeout occurs are simply returned in the\n",
    "second set.\n",
    "\n",
    "*return_when* indicates when this function should return. It must be one\n",
    "of the following constants:\n",
    "\n",
    "L\\|\n",
    "\n",
    "| Constant          | Description                                                                                                                                           |\n",
    "|------------------------------|-----------------------------------------|\n",
    "| `FIRST_COMPLETED` | The function will return when any future finishes or is cancelled.                                                                                    |\n",
    "| `FIRST_EXCEPTION` | The function will return when any future finishes by raising an exception. If no future raises an exception then it is equivalent to `ALL_COMPLETED`. |\n",
    "| `ALL_COMPLETED`   | The function will return when all futures finish or are cancelled.                                                                                    |\n",
    "\n",
    "Unlike `~asyncio.wait_for`, `wait()` does not cancel the futures when a\n",
    "timeout occurs.\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "3.11 Passing coroutine objects to `wait()` directly is forbidden.\n",
    "\n",
    "as_completed(aws, \\*, timeout=None)\n",
    "\n",
    "Run `awaitable objects <asyncio-awaitables>` in the *aws* iterable\n",
    "concurrently. Return an iterator of coroutines. Each coroutine returned\n",
    "can be awaited to get the earliest next result from the iterable of the\n",
    "remaining awaitables.\n",
    "\n",
    "Raises `TimeoutError` if the timeout occurs before all Futures are done.\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "Example:\n",
    "\n",
    "    for coro in as_completed(aws):\n",
    "        earliest_result = await coro\n",
    "        # ...\n",
    "\n",
    "3.10 Removed the *loop* parameter.\n",
    "\n",
    "3.10 Deprecation warning is emitted if not all awaitable objects in the\n",
    "*aws* iterable are Future-like objects and there is no running event\n",
    "loop.\n",
    "\n",
    "## Running in Threads\n",
    "\n",
    "to_thread(func, /, *args,*\\*kwargs)\n",
    "\n",
    "Asynchronously run function *func* in a separate thread.\n",
    "\n",
    "Any \\*args and \\*\\*kwargs supplied for this function are directly passed\n",
    "to *func*. Also, the current `contextvars.Context` is propagated,\n",
    "allowing context variables from the event loop thread to be accessed in\n",
    "the separate thread.\n",
    "\n",
    "Return a coroutine that can be awaited to get the eventual result of\n",
    "*func*.\n",
    "\n",
    "This coroutine function is primarily intended to be used for executing\n",
    "IO-bound functions/methods that would otherwise block the event loop if\n",
    "they were run in the main thread. For example:\n",
    "\n",
    "    def blocking_io():\n",
    "        print(f\"start blocking_io at {time.strftime('%X')}\")\n",
    "        # Note that time.sleep() can be replaced with any blocking\n",
    "        # IO-bound operation, such as file operations.\n",
    "        time.sleep(1)\n",
    "        print(f\"blocking_io complete at {time.strftime('%X')}\")\n",
    "\n",
    "    async def main():\n",
    "        print(f\"started main at {time.strftime('%X')}\")\n",
    "\n",
    "        await asyncio.gather(\n",
    "            asyncio.to_thread(blocking_io),\n",
    "            asyncio.sleep(1))\n",
    "\n",
    "        print(f\"finished main at {time.strftime('%X')}\")\n",
    "\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "    # Expected output:\n",
    "    #\n",
    "    # started main at 19:50:53\n",
    "    # start blocking_io at 19:50:53\n",
    "    # blocking_io complete at 19:50:54\n",
    "    # finished main at 19:50:54\n",
    "\n",
    "Directly calling <span class=\"title-ref\">blocking_io()</span> in any\n",
    "coroutine would block the event loop for its duration, resulting in an\n",
    "additional 1 second of run time. Instead, by using <span\n",
    "class=\"title-ref\">asyncio.to_thread()</span>, we can run it in a\n",
    "separate thread without blocking the event loop.\n",
    "\n",
    "Note\n",
    "\n",
    "Due to the `GIL`, <span class=\"title-ref\">asyncio.to_thread()</span> can\n",
    "typically only be used to make IO-bound functions non-blocking. However,\n",
    "for extension modules that release the GIL or alternative Python\n",
    "implementations that don't have one, <span\n",
    "class=\"title-ref\">asyncio.to_thread()</span> can also be used for\n",
    "CPU-bound functions.\n",
    "\n",
    "3.9\n",
    "\n",
    "## Scheduling From Other Threads\n",
    "\n",
    "run_coroutine_threadsafe(coro, loop)\n",
    "\n",
    "Submit a coroutine to the given event loop. Thread-safe.\n",
    "\n",
    "Return a `concurrent.futures.Future` to wait for the result from another\n",
    "OS thread.\n",
    "\n",
    "This function is meant to be called from a different OS thread than the\n",
    "one where the event loop is running. Example:\n",
    "\n",
    "    # Create a coroutine\n",
    "    coro = asyncio.sleep(1, result=3)\n",
    "\n",
    "    # Submit the coroutine to a given loop\n",
    "    future = asyncio.run_coroutine_threadsafe(coro, loop)\n",
    "\n",
    "    # Wait for the result with an optional timeout argument\n",
    "    assert future.result(timeout) == 3\n",
    "\n",
    "If an exception is raised in the coroutine, the returned Future will be\n",
    "notified. It can also be used to cancel the task in the event loop:\n",
    "\n",
    "    try:\n",
    "        result = future.result(timeout)\n",
    "    except TimeoutError:\n",
    "        print('The coroutine took too long, cancelling the task...')\n",
    "        future.cancel()\n",
    "    except Exception as exc:\n",
    "        print(f'The coroutine raised an exception: {exc!r}')\n",
    "    else:\n",
    "        print(f'The coroutine returned: {result!r}')\n",
    "\n",
    "See the `concurrency and multithreading <asyncio-multithreading>`\n",
    "section of the documentation.\n",
    "\n",
    "Unlike other asyncio functions this function requires the *loop*\n",
    "argument to be passed explicitly.\n",
    "\n",
    "3.5.1\n",
    "\n",
    "## Introspection\n",
    "\n",
    "current_task(loop=None)\n",
    "\n",
    "Return the currently running `Task` instance, or `None` if no task is\n",
    "running.\n",
    "\n",
    "If *loop* is `None` `get_running_loop` is used to get the current loop.\n",
    "\n",
    "3.7\n",
    "\n",
    "all_tasks(loop=None)\n",
    "\n",
    "Return a set of not yet finished `Task` objects run by the loop.\n",
    "\n",
    "If *loop* is `None`, `get_running_loop` is used for getting current\n",
    "loop.\n",
    "\n",
    "3.7\n",
    "\n",
    "## Task Object\n",
    "\n",
    "A `Future-like <Future>` object that runs a Python\n",
    "`coroutine <coroutine>`. Not thread-safe.\n",
    "\n",
    "Tasks are used to run coroutines in event loops. If a coroutine awaits\n",
    "on a Future, the Task suspends the execution of the coroutine and waits\n",
    "for the completion of the Future. When the Future is *done*, the\n",
    "execution of the wrapped coroutine resumes.\n",
    "\n",
    "Event loops use cooperative scheduling: an event loop runs one Task at a\n",
    "time. While a Task awaits for the completion of a Future, the event loop\n",
    "runs other Tasks, callbacks, or performs IO operations.\n",
    "\n",
    "Use the high-level `asyncio.create_task` function to create Tasks, or\n",
    "the low-level `loop.create_task` or `ensure_future` functions. Manual\n",
    "instantiation of Tasks is discouraged.\n",
    "\n",
    "To cancel a running Task use the `cancel` method. Calling it will cause\n",
    "the Task to throw a `CancelledError` exception into the wrapped\n",
    "coroutine. If a coroutine is awaiting on a Future object during\n",
    "cancellation, the Future object will be cancelled.\n",
    "\n",
    "`cancelled` can be used to check if the Task was cancelled. The method\n",
    "returns `True` if the wrapped coroutine did not suppress the\n",
    "`CancelledError` exception and was actually cancelled.\n",
    "\n",
    "`asyncio.Task` inherits from `Future` all of its APIs except\n",
    "`Future.set_result` and `Future.set_exception`.\n",
    "\n",
    "Tasks support the `contextvars` module. When a Task is created it copies\n",
    "the current context and later runs its coroutine in the copied context.\n",
    "\n",
    "3.7 Added support for the `contextvars` module.\n",
    "\n",
    "3.8 Added the *name* parameter.\n",
    "\n",
    "3.10 Deprecation warning is emitted if *loop* is not specified and there\n",
    "is no running event loop.\n",
    "\n",
    "cancel(msg=None)\n",
    "\n",
    "Request the Task to be cancelled.\n",
    "\n",
    "This arranges for a `CancelledError` exception to be thrown into the\n",
    "wrapped coroutine on the next cycle of the event loop.\n",
    "\n",
    "The coroutine then has a chance to clean up or even deny the request by\n",
    "suppressing the exception with a `try` ... ... `except CancelledError`\n",
    "... `finally` block. Therefore, unlike `Future.cancel`, `Task.cancel`\n",
    "does not guarantee that the Task will be cancelled, although suppressing\n",
    "cancellation completely is not common and is actively discouraged.\n",
    "\n",
    "3.9 Added the *msg* parameter.\n",
    "\n",
    "3.11 3.14 *msg* parameter is ambiguous when multiple `cancel` are called\n",
    "with different cancellation messages. The argument will be removed.\n",
    "\n",
    "The following example illustrates how coroutines can intercept the\n",
    "cancellation request:\n",
    "\n",
    "    async def cancel_me():\n",
    "        print('cancel_me(): before sleep')\n",
    "\n",
    "        try:\n",
    "            # Wait for 1 hour\n",
    "            await asyncio.sleep(3600)\n",
    "        except asyncio.CancelledError:\n",
    "            print('cancel_me(): cancel sleep')\n",
    "            raise\n",
    "        finally:\n",
    "            print('cancel_me(): after sleep')\n",
    "\n",
    "    async def main():\n",
    "        # Create a \"cancel_me\" Task\n",
    "        task = asyncio.create_task(cancel_me())\n",
    "\n",
    "        # Wait for 1 second\n",
    "        await asyncio.sleep(1)\n",
    "\n",
    "        task.cancel()\n",
    "        try:\n",
    "            await task\n",
    "        except asyncio.CancelledError:\n",
    "            print(\"main(): cancel_me is cancelled now\")\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "    # Expected output:\n",
    "    #\n",
    "    #     cancel_me(): before sleep\n",
    "    #     cancel_me(): cancel sleep\n",
    "    #     cancel_me(): after sleep\n",
    "    #     main(): cancel_me is cancelled now\n",
    "\n",
    "cancelled()\n",
    "\n",
    "Return `True` if the Task is *cancelled*.\n",
    "\n",
    "The Task is *cancelled* when the cancellation was requested with\n",
    "`cancel` and the wrapped coroutine propagated the `CancelledError`\n",
    "exception thrown into it.\n",
    "\n",
    "done()\n",
    "\n",
    "Return `True` if the Task is *done*.\n",
    "\n",
    "A Task is *done* when the wrapped coroutine either returned a value,\n",
    "raised an exception, or the Task was cancelled.\n",
    "\n",
    "result()\n",
    "\n",
    "Return the result of the Task.\n",
    "\n",
    "If the Task is *done*, the result of the wrapped coroutine is returned\n",
    "(or if the coroutine raised an exception, that exception is re-raised.)\n",
    "\n",
    "If the Task has been *cancelled*, this method raises a `CancelledError`\n",
    "exception.\n",
    "\n",
    "If the Task's result isn't yet available, this method raises a\n",
    "`InvalidStateError` exception.\n",
    "\n",
    "exception()\n",
    "\n",
    "Return the exception of the Task.\n",
    "\n",
    "If the wrapped coroutine raised an exception that exception is returned.\n",
    "If the wrapped coroutine returned normally this method returns `None`.\n",
    "\n",
    "If the Task has been *cancelled*, this method raises a `CancelledError`\n",
    "exception.\n",
    "\n",
    "If the Task isn't *done* yet, this method raises an `InvalidStateError`\n",
    "exception.\n",
    "\n",
    "add_done_callback(callback, \\*, context=None)\n",
    "\n",
    "Add a callback to be run when the Task is *done*.\n",
    "\n",
    "This method should only be used in low-level callback-based code.\n",
    "\n",
    "See the documentation of `Future.add_done_callback` for more details.\n",
    "\n",
    "remove_done_callback(callback)\n",
    "\n",
    "Remove *callback* from the callbacks list.\n",
    "\n",
    "This method should only be used in low-level callback-based code.\n",
    "\n",
    "See the documentation of `Future.remove_done_callback` for more details.\n",
    "\n",
    "get_stack(\\*, limit=None)\n",
    "\n",
    "Return the list of stack frames for this Task.\n",
    "\n",
    "If the wrapped coroutine is not done, this returns the stack where it is\n",
    "suspended. If the coroutine has completed successfully or was cancelled,\n",
    "this returns an empty list. If the coroutine was terminated by an\n",
    "exception, this returns the list of traceback frames.\n",
    "\n",
    "The frames are always ordered from oldest to newest.\n",
    "\n",
    "Only one stack frame is returned for a suspended coroutine.\n",
    "\n",
    "The optional *limit* argument sets the maximum number of frames to\n",
    "return; by default all available frames are returned. The ordering of\n",
    "the returned list differs depending on whether a stack or a traceback is\n",
    "returned: the newest frames of a stack are returned, but the oldest\n",
    "frames of a traceback are returned. (This matches the behavior of the\n",
    "traceback module.)\n",
    "\n",
    "print_stack(\\*, limit=None, file=None)\n",
    "\n",
    "Print the stack or traceback for this Task.\n",
    "\n",
    "This produces output similar to that of the traceback module for the\n",
    "frames retrieved by `get_stack`.\n",
    "\n",
    "The *limit* argument is passed to `get_stack` directly.\n",
    "\n",
    "The *file* argument is an I/O stream to which the output is written; by\n",
    "default output is written to `sys.stderr`.\n",
    "\n",
    "get_coro()\n",
    "\n",
    "Return the coroutine object wrapped by the `Task`.\n",
    "\n",
    "3.8\n",
    "\n",
    "get_name()\n",
    "\n",
    "Return the name of the Task.\n",
    "\n",
    "If no name has been explicitly assigned to the Task, the default asyncio\n",
    "Task implementation generates a default name during instantiation.\n",
    "\n",
    "3.8\n",
    "\n",
    "set_name(value)\n",
    "\n",
    "Set the name of the Task.\n",
    "\n",
    "The *value* argument can be any object, which is then converted to a\n",
    "string.\n",
    "\n",
    "In the default Task implementation, the name will be visible in the\n",
    "`repr` output of a task object.\n",
    "\n",
    "3.8"
   ],
   "id": "48a6d7da-8ea8-4f72-8f81-8c2abfe63b54"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
